zookeeper:
  image: javabilities/docker-zookeeper
  name: zookeeper
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
kafka:
  image: javabilities/docker-kafka
  name: kafka
  ports:
    - "9092:9092"
  environment:
    ADVERTISED_HOST_NAME: "kafka"
    ZOOKEEPER_CONNECT: "zookeeper:2181"
  links:
    - zookeeper
producer:
  build: producer
  name: producer
  ports:
    - "8100:8100"
  links:
    - zookeeper
    - kafka
consumer:
  build: consumer
  name: consumer
  ports:
    - "8200:8200"
  links:
    - zookeeper
    - kafka
