spring:
  thymeleaf:
    cache: false

zookeeper:
  host: localhost
  port: 2181
  sessionTimeoutMs: 10000
  connectionTimeoutMs: 10000

kafka:
  host: localhost
  port: 9092
  soTimeout: 100000
  bufferSize: 65536
  clientId: producer
  serializerClass: kafka.serializer.StringEncoder
  partitionerClass: com.javabilities.producer.service.SimplePartitioner
  requestRequiredAcks: 1
  numPartitions: 1
  replicationFactor: 1

topics:
  - key: test
    handlerName: test
  - key: signalMetadata
    handlerName: signalMetadata-ingest
  - key: gatewayStatusMessage
    handlerName: gatewayStatusMessage-ingest
  - key: uplinkPayloadMetadata
    handlerName: uplinkPayloadMetadata-ingest
  - key: downlink
    handlerName: downlink
